[versions]
adventure = "4.26.1"
blossom = "2.2.0"
cloud-core = "2.0.0-rc.2"
cloud-minecraft = "2.0.0-beta.14"
configurate-yaml = "4.2.0"
connectorplugin = "1.5.2-SNAPSHOT"
fastutil = "8.5.2"
guava = "33.5.0-jre"
hibernate = "7.2.0.Final"
indra = "4.0.0"
liquibase = "5.0.1"
liquibase-slf4j = "5.1.0"
log4j-slf4j-impl = "2.25.3"
lombok = "9.1.0"
luckperms-api = "5.5"
paper-api = "1.21.11-R0.1-SNAPSHOT"
postgresql = "42.7.8"
shadow = "9.3.0"
spotless = "8.1.0"
velocity-api = "3.4.0-SNAPSHOT"

[libraries]
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud-core" }
cloud-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-minecraft" }
cloud-velocity = { group = "org.incendo", name = "cloud-velocity", version.ref = "cloud-minecraft" }
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate-yaml" }
connectorplugin-bukkit = { group = "de.themoep.connectorplugin", name = "bukkit", version.ref = "connectorplugin" }
connectorplugin-core = { group = "de.themoep.connectorplugin", name = "core", version.ref = "connectorplugin" }
connectorplugin-velocity = { group = "de.themoep.connectorplugin", name = "velocity", version.ref = "connectorplugin" }
fastutil-object-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-object-object-maps", version.ref = "fastutil" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
hibernate-core = { group = "org.hibernate.orm", name = "hibernate-core", version.ref = "hibernate" }
hibernate-hikaricp = { group = "org.hibernate", name = "hibernate-hikaricp", version.ref = "hibernate" }
liquibase-core = { group = "org.liquibase", name = "liquibase-core", version.ref = "liquibase" }
liquibase-slf4j = { group = "com.mattbertolini", name = "liquibase-slf4j", version.ref = "liquibase-slf4j" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4j-slf4j-impl" }
luckperms-api = { group = "net.luckperms", name = "api", version.ref = "luckperms-api" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity-api" }

[bundles]
adventure-paper = [
    "adventure-api",
    "adventure-text-minimessage"
]
adventure-core = ["adventure-api", "adventure-text-minimessage"]
adventure-velocity = ["adventure-api", "adventure-text-minimessage"]
cloud-core = ["cloud-core", "cloud-minecraft-extras"]
cloud-paper = ["cloud-paper", "cloud-minecraft-extras"]
cloud-velocity = ["cloud-velocity", "cloud-minecraft-extras"]
database = [
    "hibernate-core", 
    "hibernate-hikaricp",
    "postgresql"
]
fastutil = ["fastutil-object-object-maps"]
liquibase = [
    "hibernate-core", 
    "hibernate-hikaricp",
    "liquibase-core",
    "liquibase-slf4j",
    "postgresql"
]

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.gradle.spotless", version.ref = "spotless" }